[project]
name = "src"
version = "0.0.1"
description = "This is the project related to Vehicle Insurance Domain"
authors = [{name = "Rajkumar Solanki", email = "rajsoluky5323@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}